
name: README
on:
  push:
    branches:
      - 'main'
    paths:
      - 'HEADER.md'
      - 'docs/source/index.md'
      - 'docs/source/assets/logo.svg'
      - '.github/workflows/readme.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - run: julia --color=yes readme.jl
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add . && git commit -m "Regenerate README.md")
          git push
